package org.baps.api.vtms.enumerations;

import lombok.Getter;

@Getter
public enum PermissionEnum {

    VIEW_AVAILABLE_PERSONNEL_LIST,
    VIEW_PERSONNEL_LIST,
        
    VIEW_ROLE_LIST,

    VIEW_SERVICE_TEMPLATE_LIST,

    ADD_VISIT,
    UPDATE_VISIT,
    VIEW_VISIT,
    VIEW_VISIT_LIST,
    VIEW_VISIT_ALL_LIST,
    VIEW_VISIT_SELF_ASSIGN_LIST,
    UPDATE_VISIT_STAGE,
    VIEW_VISIT_STAGE_LIST,

    ADD_VISIT_DOCUMENT,
    DELETE_VISIT_DOCUMENT,
    VIEW_VISIT_DOCUMENT_LIST,

    ADD_VISIT_EXTERNAL_FEEDBACK,
    VIEW_VISIT_EXTERNAL_FEEDBACK,
    
    ADD_VISIT_INTERNAL_FEEDBACK,
    VIEW_VISIT_INTERNAL_FEEDBACK,
    DELETE_VISIT_INTERNAL_FEEDBACK,
    CHECK_VISIT_EXTERNAL_FEEDBACK_EXISTS,

    ADD_VISIT_SERVICE,
    UPDATE_VISIT_SERVICE,
    VIEW_VISIT_SERVICE_LIST,
    VIEW_VISIT_SERVICE,
    DELETE_VISIT_SERVICE,

    UPDATE_VISIT_TEAM,
    VIEW_VISIT_TEAM,

    ADD_VISIT_TOUR,
    UPDATE_VISIT_TOUR,
    VIEW_VISIT_TOUR,

    VIEW_VISIT_SCHEDULE,

    VIEW_VISIT_INTERVIEW_SETUP,
    UPDATE_VISIT_INTERVIEW_SETUP,
    DELETE_VISIT_INTERVIEW_SETUP,

    CREATE_TOUR_SLOT,
    UPDATE_TOUR_SLOT,
    VIEW_TOUR_SLOT_LIST,
    UPDATE_TOUR_SLOT_STAGE,
    VIEW_TOUR_LIST_VISIT_ASSOCIATED,

    UPDATE_PRE_BOOKED_VISIT,
    VIEW_PRE_BOOKED_VISIT,
    VIEW_PRE_BOOKED_VISIT_LIST,
    VIEW_PRE_BOOKED_VISIT_ALL_LIST,
    VIEW_PRE_BOOKED_VISIT_SELF_ASSIGN_LIST,
    

    VIEW_DASHBOARD_VISIT_COUNT,
    VIEW_DASHBOARD_VISIT_SUMMARY,
    VIEW_DASHBOARD_PREBOOKED_VISIT_SUMMARY,
    VIEW_DASHBOARD_PREBOOKED_VISIT_FEEDBACK_SUMMARY;
}
